version: '3.8'
services:
  sim-smart-gsm:
    environment:
      vps-id: 72.60.41.168
      device: my-gsm-node-01
      scan-interval-ms: 60000

    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always

